spring.application.name=hospital-management

spring.datasource.url=jdbc:mysql://localhost:3306/hospital
spring.datasource.username=root
spring.datasource.password=150700ch

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true